// ----------------------------------------------------------------------------------------------
// <auto-generated>
// This file was autogenerated by QuantumBindingGenerator.
// Do not edit this file manually, because you will lose all your changes after next generation.
// </auto-generated>
// ----------------------------------------------------------------------------------------------

namespace QuantumBinding.Clang.Interop
{
    using System.Security;
    using System;
    using System.Runtime.InteropServices;

    ///<summary>
    /// Visitor invoked for each cursor found by a traversal.
    ///</summary>
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate CXChildVisitResult CXCursorVisitor([In] QuantumBinding.Clang.Interop.CXCursor cursor, [In] QuantumBinding.Clang.Interop.CXCursor parent, [In] QuantumBinding.Clang.Interop.CXClientData client_data);
    ///<summary>
    /// Visitor invoked for each file in a translation unit (used with clang_getInclusions()).
    ///</summary>
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void CXInclusionVisitor([In] QuantumBinding.Clang.Interop.CXFile included_file, [In] QuantumBinding.Clang.Interop.CXSourceLocation inclusion_stack, [In] uint include_len, [In] QuantumBinding.Clang.Interop.CXClientData client_data);
    ///<summary>
    /// Visitor invoked for each field found by a traversal.
    ///</summary>
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate CXVisitorResult CXFieldVisitor([In] QuantumBinding.Clang.Interop.CXCursor C, [In] QuantumBinding.Clang.Interop.CXClientData client_data);

}

