// ----------------------------------------------------------------------------------------------
// <auto-generated>
// This file was autogenerated by QuantumBindingGenerator.
// Do not edit this file manually, because you will lose all your changes after next generation.
// </auto-generated>
// ----------------------------------------------------------------------------------------------

namespace QuantumBinding.Clang.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using QuantumBinding.Clang;

    ///<summary>
    /// A character string.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXString
    {
        public System.IntPtr data;

        public uint private_flags;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXStringSet
    {
        public System.IntPtr Strings;

        public uint Count;

    }

    ///<summary>
    /// Object encapsulating information about overlaying virtual file/directories over the real file system.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXVirtualFileOverlay
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXVirtualFileOverlay c)
        {
            return c.pointer;
        }

        public static implicit operator CXVirtualFileOverlay(System.IntPtr c)
        {
            return new CXVirtualFileOverlay(){pointer = c};
        }

    }

    ///<summary>
    /// Object encapsulating information about a module.map file.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXModuleMapDescriptor
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXModuleMapDescriptor c)
        {
            return c.pointer;
        }

        public static implicit operator CXModuleMapDescriptor(System.IntPtr c)
        {
            return new CXModuleMapDescriptor(){pointer = c};
        }

    }

    ///<summary>
    /// An "index" that consists of a set of translation units that would typically be linked together into an executable or library.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIndex
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXIndex c)
        {
            return c.pointer;
        }

        public static implicit operator CXIndex(System.IntPtr c)
        {
            return new CXIndex(){pointer = c};
        }

    }

    ///<summary>
    /// An opaque type representing target information for a given translation unit.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXTargetInfo
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXTargetInfo c)
        {
            return c.pointer;
        }

        public static implicit operator CXTargetInfo(System.IntPtr c)
        {
            return new CXTargetInfo(){pointer = c};
        }

    }

    ///<summary>
    /// A single translation unit, which resides in an index.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXTranslationUnit
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXTranslationUnit c)
        {
            return c.pointer;
        }

        public static implicit operator CXTranslationUnit(System.IntPtr c)
        {
            return new CXTranslationUnit(){pointer = c};
        }

    }

    ///<summary>
    /// Opaque pointer representing client data that will be passed through to various callbacks and visitors.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXClientData
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXClientData c)
        {
            return c.pointer;
        }

        public static implicit operator CXClientData(System.IntPtr c)
        {
            return new CXClientData(){pointer = c};
        }

    }

    ///<summary>
    /// Provides the contents of a file that has not yet been saved to disk.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXUnsavedFile
    {
        ///<summary>
        /// The file whose contents have not yet been saved.
        ///</summary>
        public System.IntPtr Filename;

        ///<summary>
        /// A buffer containing the unsaved contents of this file.
        ///</summary>
        public System.IntPtr Contents;

        ///<summary>
        /// The length of the unsaved contents of this buffer.
        ///</summary>
        public uint Length;

    }

    ///<summary>
    /// Describes a version number of the form major.minor.subminor.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXVersion
    {
        ///<summary>
        /// The major version number, e.g., the '10' in '10.7.3'. A negative value indicates that there is no version number at all.
        ///</summary>
        public int Major;

        ///<summary>
        /// The minor version number, e.g., the '7' in '10.7.3'. This value will be negative if no minor version number was provided, e.g., for version '10'.
        ///</summary>
        public int Minor;

        ///<summary>
        /// The subminor version number, e.g., the '3' in '10.7.3'. This value will be negative if no minor or subminor version number was provided, e.g., in version '10' or '10.7'.
        ///</summary>
        public int Subminor;

    }

    ///<summary>
    /// A particular source file that is part of a translation unit.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXFile
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXFile c)
        {
            return c.pointer;
        }

        public static implicit operator CXFile(System.IntPtr c)
        {
            return new CXFile(){pointer = c};
        }

    }

    ///<summary>
    /// Uniquely identifies a CXFile, that refers to the same underlying file, across an indexing session.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXFileUniqueID
    {
        public unsafe fixed ulong data[3];

    }

    ///<summary>
    /// Identifies a specific source location within a translation unit.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXSourceLocation
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
        public System.IntPtr[] ptr_data;

        public uint int_data;

    }

    ///<summary>
    /// Identifies a half-open character range in the source code.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXSourceRange
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
        public System.IntPtr[] ptr_data;

        public uint begin_int_data;

        public uint end_int_data;

    }

    ///<summary>
    /// Identifies an array of ranges.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXSourceRangeList
    {
        ///<summary>
        /// The number of ranges in the ranges array.
        ///</summary>
        public uint count;

        ///<summary>
        /// An array of CXSourceRanges.
        ///</summary>
        public System.IntPtr ranges;

    }

    ///<summary>
    /// A single diagnostic, containing the diagnostic's severity, location, text, source ranges, and fix-it hints.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXDiagnostic
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXDiagnostic c)
        {
            return c.pointer;
        }

        public static implicit operator CXDiagnostic(System.IntPtr c)
        {
            return new CXDiagnostic(){pointer = c};
        }

    }

    ///<summary>
    /// A group of CXDiagnostics.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXDiagnosticSet
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXDiagnosticSet c)
        {
            return c.pointer;
        }

        public static implicit operator CXDiagnosticSet(System.IntPtr c)
        {
            return new CXDiagnosticSet(){pointer = c};
        }

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXTUResourceUsageEntry
    {
        ///<summary>
        /// The memory usage category.
        ///</summary>
        public CXTUResourceUsageKind kind;

        ///<summary>
        /// Amount of resources used. The units will depend on the resource kind.
        ///</summary>
        public uint amount;

    }

    ///<summary>
    /// The memory usage of a CXTranslationUnit, broken into categories.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXTUResourceUsage
    {
        ///<summary>
        /// Private data member, used for queries.
        ///</summary>
        public System.IntPtr data;

        ///<summary>
        /// The number of entries in the 'entries' array.
        ///</summary>
        public uint numEntries;

        ///<summary>
        /// An array of key-value pairs, representing the breakdown of memory usage.
        ///</summary>
        public System.IntPtr entries;

    }

    ///<summary>
    /// A cursor representing some element in the abstract syntax tree for a translation unit.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXCursor
    {
        public CXCursorKind kind;

        public int xdata;

        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
        public System.IntPtr[] data;

    }

    ///<summary>
    /// Describes the availability of a given entity on a particular platform, e.g., a particular class might only be available on Mac OS 10.7 or newer.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXPlatformAvailability
    {
        ///<summary>
        /// A string that describes the platform for which this structure provides availability information.
        ///</summary>
        public CXString Platform;

        ///<summary>
        /// The version number in which this entity was introduced.
        ///</summary>
        public CXVersion Introduced;

        ///<summary>
        /// The version number in which this entity was deprecated (but is still available).
        ///</summary>
        public CXVersion Deprecated;

        ///<summary>
        /// The version number in which this entity was obsoleted, and therefore is no longer available.
        ///</summary>
        public CXVersion Obsoleted;

        ///<summary>
        /// Whether the entity is unconditionally unavailable on this platform.
        ///</summary>
        public int Unavailable;

        ///<summary>
        /// An optional message to provide to a user of this API, e.g., to suggest replacement APIs.
        ///</summary>
        public CXString Message;

    }

    ///<summary>
    /// A fast container representing a set of CXCursors.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXCursorSet
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXCursorSet c)
        {
            return c.pointer;
        }

        public static implicit operator CXCursorSet(System.IntPtr c)
        {
            return new CXCursorSet(){pointer = c};
        }

    }

    ///<summary>
    /// The type of an element in the abstract syntax tree.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXType
    {
        public CXTypeKind kind;

        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
        public System.IntPtr[] data;

    }

    ///<summary>
    /// Opaque pointer representing a policy that controls pretty printing for clang_getCursorPrettyPrinted.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXPrintingPolicy
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXPrintingPolicy c)
        {
            return c.pointer;
        }

        public static implicit operator CXPrintingPolicy(System.IntPtr c)
        {
            return new CXPrintingPolicy(){pointer = c};
        }

    }

    ///<summary>
    /// The functions in this group provide access to information about modules.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXModule
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXModule c)
        {
            return c.pointer;
        }

        public static implicit operator CXModule(System.IntPtr c)
        {
            return new CXModule(){pointer = c};
        }

    }

    ///<summary>
    /// Describes a single preprocessing token.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXToken
    {
        public unsafe fixed uint int_data[4];

        public System.IntPtr ptr_data;

    }

    ///<summary>
    /// A semantic string that describes a code-completion result.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXCompletionString
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXCompletionString c)
        {
            return c.pointer;
        }

        public static implicit operator CXCompletionString(System.IntPtr c)
        {
            return new CXCompletionString(){pointer = c};
        }

    }

    ///<summary>
    /// A single result of code completion.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXCompletionResult
    {
        ///<summary>
        /// The kind of entity that this completion refers to.
        ///</summary>
        public CXCursorKind CursorKind;

        ///<summary>
        /// The code-completion string that describes how to insert this code-completion result into the editing buffer.
        ///</summary>
        public CXCompletionString CompletionString;

    }

    ///<summary>
    /// Contains the results of code-completion.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXCodeCompleteResults
    {
        ///<summary>
        /// The code-completion results.
        ///</summary>
        public System.IntPtr Results;

        ///<summary>
        /// The number of code-completion results stored in the Results array.
        ///</summary>
        public uint NumResults;

    }

    ///<summary>
    /// Evaluation result of a cursor
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXEvalResult
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXEvalResult c)
        {
            return c.pointer;
        }

        public static implicit operator CXEvalResult(System.IntPtr c)
        {
            return new CXEvalResult(){pointer = c};
        }

    }

    ///<summary>
    /// A remapping of original source files and their translated files.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXRemapping
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXRemapping c)
        {
            return c.pointer;
        }

        public static implicit operator CXRemapping(System.IntPtr c)
        {
            return new CXRemapping(){pointer = c};
        }

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXCursorAndRangeVisitor
    {
        public System.IntPtr context;

        public System.IntPtr visit;

    }

    ///<summary>
    /// The client's data object that is associated with a CXFile.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxClientFile
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXIdxClientFile c)
        {
            return c.pointer;
        }

        public static implicit operator CXIdxClientFile(System.IntPtr c)
        {
            return new CXIdxClientFile(){pointer = c};
        }

    }

    ///<summary>
    /// The client's data object that is associated with a semantic entity.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxClientEntity
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXIdxClientEntity c)
        {
            return c.pointer;
        }

        public static implicit operator CXIdxClientEntity(System.IntPtr c)
        {
            return new CXIdxClientEntity(){pointer = c};
        }

    }

    ///<summary>
    /// The client's data object that is associated with a semantic container of entities.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxClientContainer
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXIdxClientContainer c)
        {
            return c.pointer;
        }

        public static implicit operator CXIdxClientContainer(System.IntPtr c)
        {
            return new CXIdxClientContainer(){pointer = c};
        }

    }

    ///<summary>
    /// The client's data object that is associated with an AST file (PCH or module).
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxClientASTFile
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXIdxClientASTFile c)
        {
            return c.pointer;
        }

        public static implicit operator CXIdxClientASTFile(System.IntPtr c)
        {
            return new CXIdxClientASTFile(){pointer = c};
        }

    }

    ///<summary>
    /// Source location passed to index callbacks.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxLoc
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
        public System.IntPtr[] ptr_data;

        public uint int_data;

    }

    ///<summary>
    /// Data for ppIncludedFile callback.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxIncludedFileInfo
    {
        ///<summary>
        /// Location of '#' in the #include/#import directive.
        ///</summary>
        public CXIdxLoc hashLoc;

        ///<summary>
        /// Filename as written in the #include/#import directive.
        ///</summary>
        public System.IntPtr filename;

        ///<summary>
        /// The actual file that the #include/#import directive resolved to.
        ///</summary>
        public CXFile file;

        public int isImport;

        public int isAngled;

        ///<summary>
        /// Non-zero if the directive was automatically turned into a module import.
        ///</summary>
        public int isModuleImport;

    }

    ///<summary>
    /// Data for IndexerCallbacks#importedASTFile.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxImportedASTFileInfo
    {
        ///<summary>
        /// Top level AST file containing the imported PCH, module or submodule.
        ///</summary>
        public CXFile file;

        ///<summary>
        /// The imported module or NULL if the AST file is a PCH.
        ///</summary>
        public CXModule module;

        ///<summary>
        /// Location where the file is imported. Applicable only for modules.
        ///</summary>
        public CXIdxLoc loc;

        ///<summary>
        /// Non-zero if an inclusion directive was automatically turned into a module import. Applicable only for modules.
        ///</summary>
        public int isImplicit;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxAttrInfo
    {
        public CXIdxAttrKind kind;

        public CXCursor cursor;

        public CXIdxLoc loc;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxEntityInfo
    {
        public CXIdxEntityKind kind;

        public CXIdxEntityCXXTemplateKind templateKind;

        public CXIdxEntityLanguage lang;

        public System.IntPtr name;

        public System.IntPtr USR;

        public CXCursor cursor;

        public System.IntPtr attributes;

        public uint numAttributes;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxContainerInfo
    {
        public CXCursor cursor;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxIBOutletCollectionAttrInfo
    {
        public System.IntPtr attrInfo;

        public System.IntPtr objcClass;

        public CXCursor classCursor;

        public CXIdxLoc classLoc;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxDeclInfo
    {
        public System.IntPtr entityInfo;

        public CXCursor cursor;

        public CXIdxLoc loc;

        public System.IntPtr semanticContainer;

        ///<summary>
        /// Generally same as #semanticContainer but can be different in cases like out-of-line C++ member functions.
        ///</summary>
        public System.IntPtr lexicalContainer;

        public int isRedeclaration;

        public int isDefinition;

        public int isContainer;

        public System.IntPtr declAsContainer;

        ///<summary>
        /// Whether the declaration exists in code or was created implicitly by the compiler, e.g. implicit Objective-C methods for properties.
        ///</summary>
        public int isImplicit;

        public System.IntPtr attributes;

        public uint numAttributes;

        public uint flags;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxObjCContainerDeclInfo
    {
        public System.IntPtr declInfo;

        public CXIdxObjCContainerKind kind;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxBaseClassInfo
    {
        public System.IntPtr @base;

        public CXCursor cursor;

        public CXIdxLoc loc;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxObjCProtocolRefInfo
    {
        public System.IntPtr protocol;

        public CXCursor cursor;

        public CXIdxLoc loc;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxObjCProtocolRefListInfo
    {
        public System.IntPtr protocols;

        public uint numProtocols;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxObjCInterfaceDeclInfo
    {
        public System.IntPtr containerInfo;

        public System.IntPtr superInfo;

        public System.IntPtr protocols;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxObjCCategoryDeclInfo
    {
        public System.IntPtr containerInfo;

        public System.IntPtr objcClass;

        public CXCursor classCursor;

        public CXIdxLoc classLoc;

        public System.IntPtr protocols;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxObjCPropertyDeclInfo
    {
        public System.IntPtr declInfo;

        public System.IntPtr getter;

        public System.IntPtr setter;

    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxCXXClassDeclInfo
    {
        public System.IntPtr declInfo;

        public System.IntPtr bases;

        public uint numBases;

    }

    ///<summary>
    /// Data for IndexerCallbacks#indexEntityReference.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIdxEntityRefInfo
    {
        public CXIdxEntityRefKind kind;

        ///<summary>
        /// Reference cursor.
        ///</summary>
        public CXCursor cursor;

        public CXIdxLoc loc;

        ///<summary>
        /// The entity that gets referenced.
        ///</summary>
        public System.IntPtr referencedEntity;

        ///<summary>
        /// Immediate "parent" of the reference. For example:
        ///</summary>
        public System.IntPtr parentEntity;

        ///<summary>
        /// Lexical container context of the reference.
        ///</summary>
        public System.IntPtr container;

        ///<summary>
        /// Sets of symbol roles of the reference.
        ///</summary>
        public CXSymbolRole role;

    }

    ///<summary>
    /// A group of callbacks used by #clang_indexSourceFile and #clang_indexTranslationUnit.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct IndexerCallbacks
    {
        ///<summary>
        /// Called periodically to check whether indexing should be aborted. Should return 0 to continue, and non-zero to abort.
        ///</summary>
        public System.IntPtr abortQuery;

        ///<summary>
        /// Called at the end of indexing; passes the complete diagnostic set.
        ///</summary>
        public System.IntPtr diagnostic;

        public System.IntPtr enteredMainFile;

        ///<summary>
        /// Called when a file gets #included/#imported.
        ///</summary>
        public System.IntPtr ppIncludedFile;

        ///<summary>
        /// Called when a AST file (PCH or module) gets imported.
        ///</summary>
        public System.IntPtr importedASTFile;

        ///<summary>
        /// Called at the beginning of indexing a translation unit.
        ///</summary>
        public System.IntPtr startedTranslationUnit;

        public System.IntPtr indexDeclaration;

        ///<summary>
        /// Called to index a reference of an entity.
        ///</summary>
        public System.IntPtr indexEntityReference;

    }

    ///<summary>
    /// An indexing action/session, to be applied to one or multiple translation units.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXIndexAction
    {
        public System.IntPtr pointer;

        public static implicit operator System.IntPtr(CXIndexAction c)
        {
            return c.pointer;
        }

        public static implicit operator CXIndexAction(System.IntPtr c)
        {
            return new CXIndexAction(){pointer = c};
        }

    }

    ///<summary>
    /// A parsed comment.
    ///</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CXComment
    {
        public System.IntPtr ASTNode;

        public CXTranslationUnit TranslationUnit;

    }


}

